---
# I would love to simplify these tasks into a single block ittrating
# over all items, but unfortunately, ansible does not support loops on
# blocks

- name: Install mailman-core.service
  template:
    src: "systemd/mailman-core.service.j2"
    dest: "/etc/systemd/system/{{ mailman_systemd_prefix }}core.service"
    mode: '644'
  notify:
    - systemd daemon reload
    - restart mailman core

- name: Install qcluster.service
  template:
    src: "systemd/qcluster.service.j2"
    dest: "/etc/systemd/system/{{ mailman_systemd_prefix }}qcluster.service"
    mode: '644'
  notify:
    - systemd daemon reload
    - restart qcluster

- name: Install gunicorn.service
  template:
    src: "systemd/gunicorn.service.j2"
    dest: "/etc/systemd/system/{{ mailman_systemd_prefix }}gunicorn.service"
    mode: '644'
  notify:
    - systemd daemon reload
    - restart gunicorn

- name: Install mailman-django-admin-runjobs.service
  template:
    src: "systemd/mailman-django-admin-runjobs.service.j2"
    dest: "/etc/systemd/system/{{ mailman_systemd_prefix }}django-admin-runjobs@.service"
    mode: '644'
  notify:
    - systemd daemon reload

- name: Install mailman-notify.service
  template:
    src: "systemd/mailman-notify.service.j2"
    dest: "/etc/systemd/system/{{ mailman_systemd_prefix }}notify.service"
    mode: '644'
  notify:
    - systemd daemon reload

- name: Install mailman-digests.service
  template:
    src: "systemd/mailman-digests.service.j2"
    dest: "/etc/systemd/system/{{ mailman_systemd_prefix }}digests.service"
    mode: '644'
  notify:
    - systemd daemon reload

- name: Install mailman systemd timers
  template:
    src: "systemd/mailman-{{ item }}.timer.j2"
    dest: "/etc/systemd/system/{{ mailman_systemd_prefix }}{{ item }}.timer"
    mode: '644'
  with_items: "{{ mailman_systemd_timers }}"
  notify:
    - systemd daemon reload
    - enable all systemd timers
